# docker-compose run app rails new . --force --database=sqlserver
version: "3.7"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    depends_on: 
      - db
    ports: 
      - "8080:80"
  app:
    image: wordpress
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: mywordpress
    depends_on: 
      - db
      - phpmyadmin
    ports: 
      - "9000:80"